# Generated by Django 4.2.4 on 2023-09-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalTime',
        ),
    ]
